### ISSUE TITLE
Getting an error when I run Unit test, Posting the error down below.

### ISSUE THREAD

**Issue by Yashodhar61** [zerodha/pykiteconnect#109]
Traceback (most recent call last):                                                                                                                                                    File "setup.py", line 17, in <module>                                                                                                                                                 setup(                                                                                                                                                                            File "C:\yrd\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup                                                                                                  return distutils.core.setup(**attrs)                                                                                                                                              File "C:\yrd\anaconda3\lib\distutils\core.py", line 148, in setup                                                                                                                     dist.run_commands()                                                                                                                                                               File "C:\yrd\anaconda3\lib\distutils\dist.py", line 966, in run_commands                                                                                                              self.run_command(cmd)                                                                                                                                                             File "C:\yrd\anaconda3\lib\distutils\dist.py", line 985, in run_command                                                                                                               cmd_obj.run()                                                                                                                                                                     File "c:\yrd\softwares\pykiteconnect-master\.eggs\pytest_runner-5.3.0-py3.8.egg\ptr.py", line 202, in run                                                                             installed_dists = self.install_dists(dist)                                                                                                                                        File "c:\yrd\softwares\pykiteconnect-master\.eggs\pytest_runner-5.3.0-py3.8.egg\ptr.py", line 153, in install_dists                                                                   orig.test.install_dists(dist), self.install_extra_dists(dist)                                                                                                                     File "C:\yrd\anaconda3\lib\site-packages\setuptools\command\test.py", line 204, in install_dists                                                                                      tr_d = dist.fetch_build_eggs(dist.tests_require or [])                                                                                                                            File "C:\yrd\anaconda3\lib\site-packages\setuptools\dist.py", line 687, in fetch_build_eggs                                                                                           resolved_dists = pkg_resources.working_set.resolve(                                                                                                                               File "C:\yrd\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve                                                                                             raise VersionConflict(dist, req).with_context(dependent_req)                                                                                                                    pkg_resources.ContextualVersionConflict: (urllib3 1.26.3 (c:\yrd\softwares\pykiteconnect-master\.eggs\urllib3-1.26.3-py3.8.egg), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

**Comment by vividvilla** [comment]
Seems like your Python environment specific issue. You can check tests passing on various Python version and OS here - https://github.com/zerodha/pykiteconnect/runs/1782073241?check_suite_focus=true
