### ISSUE TITLE
WebSocket Sample Code Issue

### ISSUE THREAD

**Issue by ImAbhishekTomar** [zerodha/pykiteconnect#185]
This code sample is not working. https://github.com/zerodha/pykiteconnect/blob/master/examples/threaded_ticker.py

```
INFO:root:This is main thread. Will change webosocket mode every 5 seconds.
Exception in thread Thread-30 (run):
Traceback (most recent call last):
  File "/Users/abhishektomar/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/abhishektomar/anaconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/abhishektomar/anaconda3/lib/python3.11/site-packages/twisted/internet/base.py", line 1317, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/Users/abhishektomar/anaconda3/lib/python3.11/site-packages/twisted/internet/base.py", line 1299, in startRunning
    ReactorBase.startRunning(cast(ReactorBase, self))
  File "/Users/abhishektomar/anaconda3/lib/python3.11/site-packages/twisted/internet/base.py", line 843, in startRunning
    raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable
```

**Comment by ImAbhishekTomar** [comment]
Dose anyone help here...

**Comment by ranjanrak** [comment]
Please refer to the Python websocket FAQs in the KiteConnect forum [here](https://kite.trade/forum/discussion/8019/faqs-on-pykiteconnect-specific-to-python-client#websocket-streaming). Feel free to post all your kiteconnect queries on the forum for further assistance.
